# Generated by Django 5.0.1 on 2024-05-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_options_remove_contacts_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='service',
            field=models.TextField(default=1, verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
