# Generated by Django 5.0.1 on 2024-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacts_service_contacts_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontact',
            options={'verbose_name': 'Сообщение на странице', 'verbose_name_plural': 'Сообщения на странице'},
        ),
        migrations.AlterField(
            model_name='pagecontact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
